### ISSUE TITLE
Incorrect assumption in cond_wait_cleanup.

### ISSUE THREAD

**Issue by december1981** [dpw/skinny-mutex#2]
This comment in cond_wait_cleanup didn't make sense to me:

	/* Cancellation of pthread_cond_wait re-acquires fat->mutex,
	 * and we have it pinned, so we can access the fat mutex
	 * directly from the skinny mutex for once. */

So I decided to use a more brutal test for the wait cancellation, to see if it would pop (which it did). I pushed the test I made, and suggested fix (and comments as to why I believe the way you had it would fail) - and you can see the diff here:

https://github.com/dpw/skinny-mutex/compare/master...december1981:master
(You'll note line 450: "assert(!fat->held);" in fat_mutex_release was also detected as a false positive).

Not making a pull request, as the changes were hacked together quickly to assist you in exposing the issue/working toward a proper fix.

**Comment by dpw** [comment]
Thanks for reporting this issue.  And sorry it has taken me a while to respond.

You are right, the assumption in cond_wait_cleanup is wrong. fat->held can be 1, indicating that the mutex is held by another thread.  So it's not safe to call fat_mutex_release.

But there is another issue in that code: It doesn't correspond to the specification of pthread_cond_wait, which says that the mutex should be re-acquired, even in the case of cancellation.  It turns out to be fairly straightforward to fix both of these issues together.

I have also extended that test suite so that it runs all the tests with some other threads hammering the mutex (except for a couple of tests where this isn't appropriate), in a similar way to your change.  The extended test suite now passes reliably for me.
